language: python
python:
 - "3.7"
 - "3.8"
before_install:
 - pip3 install -r requirements.txt
 - pip3 install coverage coveralls
install:
 - pip3 install .
script:
 - coverage run --source=coinage -m unittest tests
after_success:
  coveralls
